/**
 * RO-Crate download functionality
 * Generates ZIP file with ro-crate-metadata.json and README
 */

import JSZip from 'jszip'
import type { ROCrateJSONLD } from '@/types/rocrate'

/**
 * Generate README content for RO-Crate
 */
function generateReadme(rocrate: ROCrateJSONLD, projectName: string): string {
  const project = rocrate['@graph'].find(
    (entity) => entity['@type']?.includes('Project') || entity['@type']?.includes('ResearchProject')
  )

  const title = (project as any)?.name || projectName
  const description = (project as any)?.description || ''

  return `# ${title}

${description}

## RO-Crate Package

This RO-Crate package contains metadata describing an Agentic Automation Canvas project.

### Contents

- \`ro-crate-metadata.json\`: RO-Crate metadata file following RO-Crate 1.1 specification
- This README: Project overview

### Standards Compliance

This RO-Crate follows:
- RO-Crate 1.1 specification
- Schema.org vocabularies (Project, ResearchProject, CreativeWork)
- W3C DCAT (Data Catalog Vocabulary)
- W3C PROV-O (Provenance Ontology)
- P-Plan (Plan Ontology)
- FRAPO (Funding, Research Administration & Projects Ontology)
- DUO (Data Use Ontology)

### Usage

This RO-Crate can be:
- Validated using RO-Crate validators
- Imported into research data management systems
- Shared as a FAIR Digital Object
- Integrated with EOSC and other research infrastructures

Generated by Agentic Automation Canvas
`
}

/**
 * Download RO-Crate as ZIP file
 */
export async function downloadROCrateZip(
  rocrate: ROCrateJSONLD,
  projectName: string
): Promise<void> {
  const zip = new JSZip()

  // Add ro-crate-metadata.json
  zip.file('ro-crate-metadata.json', JSON.stringify(rocrate, null, 2))

  // Add README
  const readme = generateReadme(rocrate, projectName)
  zip.file('README.md', readme)

  // Generate ZIP blob
  const blob = await zip.generateAsync({ type: 'blob' })

  // Create download link
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${projectName}-rocrate.zip`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
