/**
 * RO-Crate download functionality
 * Generates ZIP file with ro-crate-metadata.json, ro-crate-preview.html, and README
 */

import type JSZip from 'jszip'
import type { ROCrateJSONLD } from '@/types/rocrate'
import type { CanvasData } from '@/types/canvas'
import {
  hasCustomBenefitDisplay,
  type BenefitDisplayState,
} from '@/types/benefitDisplay'
import { computeCanvasSummary } from './canvasSummary'
import { generateCanvasPreviewHtml } from './generateCanvasPreviewHtml'
import { generateAgentInstructions } from './agent-instructions'

async function createZip(): Promise<JSZip> {
  const { default: JSZip } = await import('jszip')
  return new JSZip()
}

/**
 * Generate README content for RO-Crate
 */
function generateReadme(rocrate: ROCrateJSONLD, projectName: string): string {
  const root = rocrate['@graph'].find((entity) => entity['@id'] === './')
  const isPartial = root?.['aac:partialCanvas'] === true
  const project = rocrate['@graph'].find(
    (entity) => entity['@type']?.includes('Project') || entity['@type']?.includes('ResearchProject')
  )

  const title = typeof project?.name === 'string' ? project.name : projectName
  const description = typeof project?.description === 'string' ? project.description : ''

  return `# ${title}

${description}

## RO-Crate Package

This RO-Crate package contains metadata describing an Agentic Automation Canvas project.
${isPartial ? '\n> **Partial canvas:** This draft was exported with unanswered prompts. It does not claim conformance to the current AAC profile.\n' : ''}

### Contents

- \`ro-crate-metadata.json\`: RO-Crate metadata file (includes project, requirements, developer feasibility, etc.)
- \`ro-crate-preview.html\`: One-page canvas summary (open in browser)
- \`AGENTS.md\`: AI coding agent instructions derived from the canvas specification
- \`benefit-display.json\`: Benefit display groups for dashboard (if available)
- This README: Project overview

### Standards Compliance

This RO-Crate ${isPartial ? 'uses' : 'follows'}:
- RO-Crate specification
${isPartial ? '- AAC vocabulary terms on a best-effort basis (partial draft; AAC profile conformance is not claimed)' : '- The current Agentic Automation Canvas RO-Crate profile'}
- Schema.org vocabularies (Project, ResearchProject, CreativeWork)
- W3C DCAT (Data Catalog Vocabulary)
- W3C PROV-O (Provenance Ontology)
- P-Plan (Plan Ontology)
- FRAPO (Funding, Research Administration & Projects Ontology)
- DUO (Data Use Ontology)

### Usage

This RO-Crate can be:
- Validated using RO-Crate validators
- Imported into research data management systems
- Shared as a FAIR Digital Object
- Integrated with EOSC and other research infrastructures

Generated by Agentic Automation Canvas
`
}

function getProjectVersion(canvasData?: CanvasData): string {
  return canvasData?.project?.version || canvasData?.version || '0.1.0'
}

function addPreviewToRocrate(rocrate: ROCrateJSONLD): void {
  rocrate['@graph'].push({
    '@id': 'ro-crate-preview.html',
    '@type': 'schema:CreativeWork',
    'schema:name': 'Canvas Summary Preview',
    about: { '@id': './' },
  })
}

/**
 * Download RO-Crate as ZIP file
 */
export async function downloadROCrateZip(
  rocrate: ROCrateJSONLD,
  projectName: string,
  canvasData?: CanvasData,
  benefitDisplay?: BenefitDisplayState
): Promise<void> {
  const zip = await createZip()

  if (canvasData) {
    const summary = computeCanvasSummary(canvasData)
    const version = getProjectVersion(canvasData)
    const html = generateCanvasPreviewHtml(canvasData, summary, version)
    zip.file('ro-crate-preview.html', html)
    addPreviewToRocrate(rocrate)
  }

  // Add ro-crate-metadata.json
  zip.file('ro-crate-metadata.json', JSON.stringify(rocrate, null, 2))

  if (hasCustomBenefitDisplay(benefitDisplay)) {
    zip.file('benefit-display.json', JSON.stringify(benefitDisplay, null, 2))
  }

  // Add AGENTS.md (AI coding agent instructions)
  if (canvasData) {
    zip.file('AGENTS.md', generateAgentInstructions(canvasData))
  }

  // Add README
  const readme = generateReadme(rocrate, projectName)
  zip.file('README.md', readme)

  // Generate ZIP blob
  const blob = await zip.generateAsync({ type: 'blob' })

  // Create download link: projectName-version-rocrate.zip
  const version = getProjectVersion(canvasData)
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${projectName}-${version}-rocrate.zip`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Build RO-Crate ZIP as ArrayBuffer (for use in scripts or server-side).
 * Same contents as downloadROCrateZip but returns the buffer instead of triggering a download.
 */
export async function buildROCrateZipBuffer(
  rocrate: ROCrateJSONLD,
  projectName: string,
  canvasData?: CanvasData,
  benefitDisplay?: BenefitDisplayState
): Promise<ArrayBuffer> {
  const zip = await createZip()

  if (canvasData) {
    const summary = computeCanvasSummary(canvasData)
    const version = getProjectVersion(canvasData)
    const html = generateCanvasPreviewHtml(canvasData, summary, version)
    zip.file('ro-crate-preview.html', html)
    addPreviewToRocrate(rocrate)
  }

  zip.file('ro-crate-metadata.json', JSON.stringify(rocrate, null, 2))
  if (hasCustomBenefitDisplay(benefitDisplay)) {
    zip.file('benefit-display.json', JSON.stringify(benefitDisplay, null, 2))
  }
  if (canvasData) {
    zip.file('AGENTS.md', generateAgentInstructions(canvasData))
  }
  const readme = generateReadme(rocrate, projectName)
  zip.file('README.md', readme)
  return zip.generateAsync({ type: 'arraybuffer' })
}
