import { expect, it } from 'vitest'
import type { CanvasData } from '@/types/canvas'
import {
  hasMeaningfulCanvasContent,
  missingSimplifiedPrompts,
} from '@/utils/simplifiedCanvasState'

function emptyCanvas(): CanvasData {
  return {
    project: { title: '', description: '', projectStage: '' },
    version: '0.1.0',
    versionDate: '2026-08-11',
  }
}

it('ignores default metadata when deciding whether to show canvas actions', () => {
  expect(hasMeaningfulCanvasContent(emptyCanvas())).toBe(false)
  expect(hasMeaningfulCanvasContent({
    ...emptyCanvas(),
    project: { ...emptyCanvas().project, title: 'Project' },
  })).toBe(true)
})

it('ignores empty parents generated by simplified-field editing', () => {
  const data = emptyCanvas()
  data.userExpectations = {
    requirements: [{ id: 'req-generated', title: 'req-generated', benefits: [] }],
  }
  data.governance = {
    stages: [{ id: 'stage-generated', name: 'Planning', milestones: [{ description: '' }] }],
  }
  expect(hasMeaningfulCanvasContent(data)).toBe(false)
})

it('tracks build and long-term maintenance ownership in governance', () => {
  const data = emptyCanvas()
  data.governance = { buildTeamStatus: 'none' }
  let missing = missingSimplifiedPrompts(data).map((prompt) => prompt.id)
  expect(missing).not.toContain('build-team-status')
  expect(missing).toContain('maintenance-status')

  data.governance.buildTeamStatus = 'committed'
  missing = missingSimplifiedPrompts(data).map((prompt) => prompt.id)
  expect(missing).not.toContain('build-team-status')

  data.governance.maintenanceOwnerStatus = 'possible'
  missing = missingSimplifiedPrompts(data).map((prompt) => prompt.id)
  expect(missing).not.toContain('maintenance-status')
})


it('requires a custom item when Other is the selected potential approach', () => {
  const data = emptyCanvas()
  data.userExpectations = {
    requirements: [{
      id: 'req-1',
      title: 'req-1',
      benefits: [],
      feasibility: { technologyApproach: { approaches: ['other'] } },
    }],
  }

  expect(missingSimplifiedPrompts(data).map((prompt) => prompt.id)).toContain('solution-approaches')
  data.userExpectations.requirements![0].feasibility!.technologyApproach!.customApproaches = ['Custom approach']
  expect(missingSimplifiedPrompts(data).map((prompt) => prompt.id)).not.toContain('solution-approaches')
})
