import { describe, expect, it } from 'vitest'
import type { CanvasData } from '@/types/canvas'
import {
  hasDetailedCanvasContent,
  hasMeaningfulCanvasContent,
  missingSimplifiedPrompts,
} from '@/utils/simplifiedCanvasState'

function emptyCanvas(): CanvasData {
  return {
    project: { title: '', description: '', projectStage: '' },
    version: '0.1.0',
    versionDate: '2026-08-11',
  }
}

it('ignores default metadata when deciding whether to show canvas actions', () => {
  expect(hasMeaningfulCanvasContent(emptyCanvas())).toBe(false)
  expect(hasMeaningfulCanvasContent({
    ...emptyCanvas(),
    project: { ...emptyCanvas().project, title: 'Project' },
  })).toBe(true)
})

it('ignores empty parents generated by simplified-field editing', () => {
  const data = emptyCanvas()
  data.userExpectations = {
    requirements: [{ id: 'req-generated', title: 'req-generated', benefits: [] }],
  }
  data.governance = {
    stages: [{ id: 'stage-generated', name: 'Planning', milestones: [{ description: '' }] }],
  }
  expect(hasMeaningfulCanvasContent(data)).toBe(false)
})

it('requires people and a lead when either build or maintenance ownership is expected', () => {
  const data = emptyCanvas()
  data.developerFeasibility = { buildTeamStatus: 'none' }
  let missing = missingSimplifiedPrompts(data).map((prompt) => prompt.id)
  expect(missing).not.toContain('first-stage-team')
  expect(missing).not.toContain('lead-organization')

  data.developerFeasibility.buildTeamStatus = 'committed'
  missing = missingSimplifiedPrompts(data).map((prompt) => prompt.id)
  expect(missing).toContain('first-stage-team')
  expect(missing).toContain('lead-organization')

  data.developerFeasibility.buildTeamStatus = 'none'
  data.developerFeasibility.maintenanceOwnerStatus = 'possible'
  missing = missingSimplifiedPrompts(data).map((prompt) => prompt.id)
  expect(missing).toContain('first-stage-team')
  expect(missing).toContain('lead-organization')
})

describe('detailed-content indicator', () => {
  it('stays off for data represented entirely by the simplified canvas', () => {
    const data = emptyCanvas()
    data.userExpectations = {
      requirements: [{
        id: 'req-1',
        title: 'req-1',
        targetPopulation: 'Operators',
        benefits: [{ benefitType: 'unclassified', description: 'Less rework' }],
        feasibility: {
          technologyApproach: {
            approaches: ['intelligent-search', 'other'],
            customApproaches: ['Domain-specific evidence triage'],
          },
        },
      }],
    }
    data.governance = {
      stages: [{
        id: 'stage-1',
        name: 'Planning',
        startDate: '2026-09-01',
        endDate: '2026-09-30',
        milestones: [{ description: 'Test it' }],
      }],
    }
    expect(hasDetailedCanvasContent(data)).toBe(false)
  })

  it('turns on for content hidden from the simplified canvas', () => {
    const data = emptyCanvas()
    data.dataAccess = { datasets: [] }
    expect(hasDetailedCanvasContent(data)).toBe(false)
    data.project.keywords = ['triage']
    expect(hasDetailedCanvasContent(data)).toBe(true)
  })
})

it('requires a custom item when Other is the selected potential approach', () => {
  const data = emptyCanvas()
  data.userExpectations = {
    requirements: [{
      id: 'req-1',
      title: 'req-1',
      benefits: [],
      feasibility: { technologyApproach: { approaches: ['other'] } },
    }],
  }

  expect(missingSimplifiedPrompts(data).map((prompt) => prompt.id)).toContain('solution-approaches')
  data.userExpectations.requirements![0].feasibility!.technologyApproach!.customApproaches = ['Custom approach']
  expect(missingSimplifiedPrompts(data).map((prompt) => prompt.id)).not.toContain('solution-approaches')
})
